apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: changeserver
  labels:
    name: changeserver
spec:
  replicas: 1
  selector:
    matchLabels:
      component: changeserver
  template:
    metadata:
      labels:
        component: changeserver
    spec:
      imagePullSecrets:
      - name: ecr-key
      containers:
      - name: changeserver
        image: 977777657611.dkr.ecr.us-west-2.amazonaws.com/changeservice 
        imagePullPolicy: Always
        env:
          - name: DEPLOY_STATE
            value: "PROD"
          - name: ECR_SECRET
            value: "true"
          - name: ECR_SECRET_NAME
            value: "ecr-key"
          - name: AUTH_API_HOST
            value: "api.e2e.apigee.net"
          - name: SHIPYARD_HOST
            value: "shipyard.e2e.apigee.net"
          - name: INTERNAL_ROUTER_HOST
            value: "internal-router.apigee"
        ports:
          - containerPort: 9000
        command: ["/changeserver", "-p", "9000", "-d", "/data", "-s", "replication", "-u", "postgres://docker@10.1.15.220:5432/docker"]
