apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  labels:
    name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      imagePullSecrets:
      - name: ecr-key
      containers:
      - name: postgres
        image: 406296173526.dkr.ecr.us-east-1.amazonaws.com/postgresservice 
        imagePullPolicy: Always
        env:
          - name: DEPLOY_STATE
            value: "PROD"
          - name: ECR_SECRET
            value: "true"
          - name: ECR_SECRET_NAME
            value: "ecr-key"
          - name: AUTH_API_HOST
            value: "api.e2e.apigee.net"
          - name: SHIPYARD_HOST
            value: "shipyard.e2e.apigee.net"
          - name: INTERNAL_ROUTER_HOST
            value: "internal-router.apigee"
        ports:
          - containerPort: 9000
